"""initial_schema

Revision ID: 10c491293165
Revises:
Create Date: 2026-01-11 21:33:19.820614
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers, used by Alembic.
revision: str = "10c491293165"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packs",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column(
            "short_description", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("curator_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("curator_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("curator_verified", sa.Boolean(), nullable=False),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("difficulty", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("estimated_setup_minutes", sa.Integer(), nullable=False),
        sa.Column("target_audience", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("video_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("blog_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("example_repo_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("install_count", sa.Integer(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_packs_slug"), "packs", ["slug"], unique=True)
    op.create_table(
        "plugins",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("repository_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("homepage_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("author_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("author_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("keywords", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("github_stars", sa.Integer(), nullable=False),
        sa.Column("github_forks", sa.Integer(), nullable=False),
        sa.Column("open_issues", sa.Integer(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_deprecated", sa.Boolean(), nullable=False),
        sa.Column(
            "maintenance_status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("requires_api_keys", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requires_prerequisites", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "claude_plan_required", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("commands_count", sa.Integer(), nullable=False),
        sa.Column("agents_count", sa.Integer(), nullable=False),
        sa.Column("hooks_count", sa.Integer(), nullable=False),
        sa.Column("mcp_servers_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("last_scraped_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plugins_category"), "plugins", ["category"], unique=False)
    op.create_index(op.f("ix_plugins_name"), "plugins", ["name"], unique=False)
    op.create_index(op.f("ix_plugins_slug"), "plugins", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("github_id", sa.Integer(), nullable=False),
        sa.Column("github_username", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "github_avatar_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_curator", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    op.create_table(
        "pack_plugins",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pack_id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.Uuid(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("phase_order", sa.Integer(), nullable=False),
        sa.Column("plugin_order", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("commands_to_run", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["packs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plugin_id"],
            ["plugins.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reviews",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
        sa.Column("pro_tip", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("gotcha", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("example_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("frameworks_used", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_size", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("time_saved_hours", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plugin_id", sa.Uuid(), nullable=True),
        sa.Column("pack_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "user_github_username", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("helpful_count", sa.Integer(), nullable=False),
        sa.Column("reported_count", sa.Integer(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["packs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plugin_id"],
            ["plugins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    op.drop_table("pack_plugins")
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_plugins_slug"), table_name="plugins")
    op.drop_index(op.f("ix_plugins_name"), table_name="plugins")
    op.drop_index(op.f("ix_plugins_category"), table_name="plugins")
    op.drop_table("plugins")
    op.drop_index(op.f("ix_packs_slug"), table_name="packs")
    op.drop_table("packs")
    # ### end Alembic commands ###
